[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name tail
    Path /Users/prathams/Desktop/Bank_POC/logs/payment-processor/*.log
    Tag  payment-processor
    Parser json

[INPUT]
    Name tail
    Path /Users/prathams/Desktop/Bank_POC/logs/npci-mock/*.log
    Tag  npci-mock
    Parser json

[INPUT]
    Name tail
    Path /Users/prathams/Desktop/Bank_POC/logs/file-watcher.log
    Tag  file-watcher
    Parser json

[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}
    Record service_name bank-poc

[OUTPUT]
    Name        loki
    Match       *
    Host        localhost
    Port        3100
    Labels      job=fluent-bit, component=$Tag
    Auto_kubernetes_labels off
